
#AUTOGENERATED! You should be changing this stuff.
from config_default import *
SECRET_KEY='cecf7e1caeca7558fa347a063a8b82e37524392a0605583e4762f2a5368fd3bd891574f23a3b769e4643957ebeb2101015f778ebde82b0b16da786648dc7b448' #TODO - you should change this!

